import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import Header from "./components/Header";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const hkGrotesk = localFont({
    src: [
        {
            path: "./fonts/HKGrotesk-Thin.woff2",
            weight: "100",
            style: "normal",
        },
        {
            path: "./fonts/HKGrotesk-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "./fonts/HKGrotesk-Medium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/HKGrotesk-Bold.woff2",
            weight: "700",
            style: "normal",
        },
    ],
    variable: "--font-hk-grotesk",
})

export const metadata: Metadata = {
    title: "Gabriel's Blog",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${hkGrotesk.className} antialiased`}
            >
                <Header />
                {children}
            </body>
        </html>
    );
}
